name: notes
description: Classic Notes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: 2.0.0
  path_provider: 2.0.15
  hive_flutter: 1.1.0
  cupertino_icons: 1.0.5
  flutter_bloc: 8.1.2
  google_fonts: 4.0.3
  drag_and_drop_lists: 0.3.3
  easy_localization: 3.0.2
  equatable: 2.0.5
  intl: 0.18.1
  flutter_logs: 2.1.10
  hive: 2.2.3
  hive_generator: 2.0.0
  path_provider_android: 2.0.27
  flutter_keyboard_visibility: 5.4.1
  rich_text_editor_controller: 0.0.3
  flutter_colorpicker: 1.0.3


dev_dependencies:
  mockito: 5.4.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: 2.3.3
  flutter_lints: 2.0.1
  test: 1.24.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/localization/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
