name: Develop workflow
on: [pull_request,workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'master'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --no-tree-shake-icons
      - run: flutter build appbundle --no-tree-shake-icons